name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: pltamy/1lab:latest

    env:
      mailmap: ${{ secrets.MAILMAP }}

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Shakefile version
        run: sha256sum /bin/1lab-shake | cut -d' ' -f1 > .shake-version

      - name: Cache _build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: _build
          key: shake-${{ hashFiles('.shake-version' )}}

      - name: Build 🛠️
        run: |
          echo "$mailmap" > .mailmap
          ln -sf $NODE_DEPS_PATH .
          1lab-shake all -j
          ./support/make-site.sh

      - name: Deploy 🚀
        if: ${{ github.ref_name == 'main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: _build/site
